version: "3.9"
services:
  # Servicio de MongoDB
  mongo:
    image: mariapicazo5/p2gps:db
    deploy:
      replicas: 1 # Escalabilidad del servicio
      resources:
        limits:
          cpus: "0.15"
          memory: 200M
      restart_policy:
        condition: on-failure # Reiniciar el contenedor si falla
    ports:
      - "28017:28017" # Mapeo de puertos
      - "27017:27017"
    volumes:
      - "db-data:/data/db" # Persistencia de datos

  # Servicio de Order
  order:
    image: mariapicazo5/p2gps:order
    depends_on:
      - mongo # Dependencia del servicio Mongo
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.3"
          memory: 500M
      restart_policy:
        # condition: on-failure
    ports:
      - "8080:8080"

  # Servicio web
  web:
    image: mariapicazo5/p2gps:web
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 300M
      restart_policy:
        condition: on-failure
    ports:
      - "80:8080"

volumes:
  db-data: {}
